### ISSUE TITLE
Fault tolerance when using the Linstor driver

### ISSUE THREAD

**Issue by antnjakushin** [OpenNebula/addon-linstor#17]
Opennebula: 6.6.3
Addon Linstor: latest

We are trying to configure fault tolerance using host hooks:
```
ARGUMENTS = "$TEMPLATE -m -p 2"
ARGUMENTS_STDIN = "yes"
COMMAND   = "ft/host_error.rb"
NAME      = "host_error"
STATE     = "ERROR"
REMOTE    = "no"
RESOURCE  = HOST
TYPE      = state
```

But when this hook is triggered (the host is turned off), we get the error:
```
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/tm/linstor/mv n03:/var/lib/one//datastores/100/12 n01:/var/lib/one//datastores/100/12 12 100
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: Traceback (most recent call last):
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: File "/usr/lib/python3.6/site-packages/one/util.py", line 392, in run_main
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: main_func()
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: File "/var/lib/one/remotes/tm/linstor/mv", line 82, in main
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: raise RuntimeError("Unable to tar copy to new host")
Tue Nov 28 14:42:00 2023 [Z0][TrM][I]: RuntimeError: Unable to tar copy to new host
Tue Nov 28 14:42:00 2023 [Z0][TrM][E]: Unable to tar copy to new host
Tue Nov 28 14:42:00 2023 [Z0][TrM][E]: Error executing image transfer script: Traceback (most recent call last):   File "/usr/lib/python3.6/site-packages/one/util.py", line 392, in run_main     main_func()   File "/var/lib/on
e/remotes/tm/linstor/mv", line 82, in main     raise RuntimeError("Unable to tar copy to new host") RuntimeError: Unable to tar copy to new host ERROR: Unable to tar copy to new host
Tue Nov 28 14:42:00 2023 [Z0][VM][I]: New LCM state is PROLOG_MIGRATE_UNKNOWN_FAILURE
```
In this log file: `n03` - the host that was shutdown, `n01` - the host to which there was an attempt to migrate the VM, `12` - virtual machine ID, `100` - datastore ID.

I looked at the file `/var/lib/one/remotes/tm/linstor/mv`, and it seems to me that we are in the wrong branch of the loop , since the function `disk_id` expects a value in a different format (since now we are assigning the `None` value to the variable and trying to copy data from a switched off host).

Have I identified the problems correctly or should I look elsewhere?

**Comment by antnjakushin** [comment]
According to messages in the log file, we run the migration process twice, the second one fails with an error because incorrect arguments were passed:
```
Nov 28 14:41:55 n02 /mv[3279706]: INFO Entering tm mv, from='n03:/var/lib/one//datastores/100/12/disk.0' to='n01:/var/lib/one//datastores/100/12/disk.0'
Nov 28 14:41:55 n02 /mv[3279706]: INFO running shell command: onedatastore show --xml 101
Nov 28 14:41:56 n02 /mv[3279706]: INFO running shell command: onevm show -x 12
Nov 28 14:41:56 n02 /mv[3279706]: INFO OpenNebula-Image-17-vm12-disk0 is a non-persistent OS or DATABLOCK image
Nov 28 14:41:56 n02 /mv[3279706]: INFO Active resource 'OpenNebula-Image-17-vm12-disk0' on destination host: n01
Nov 28 14:41:56 n02 /mv[3279706]: INFO Deactivate resource 'OpenNebula-Image-17-vm12-disk0' on source host: n03
Nov 28 14:41:56 n02 /mv[3279706]: INFO ssh 'n01' cmd: mkdir -p /var/lib/one/datastores/100/12 && ln -fs /dev/drbd1032 /var/lib/one/datastores/100/12/disk.0
Nov 28 14:41:56 n02 /mv[3279706]: INFO Exiting tm mv
Nov 28 14:41:57 n02 /mv[3279901]: INFO Entering tm mv, from='n03:/var/lib/one//datastores/100/12' to='n01:/var/lib/one//datastores/100/12'
Nov 28 14:41:57 n02 /mv[3279901]: INFO running shell command: onedatastore show --xml 100
Nov 28 14:41:57 n02 /mv[3279901]: INFO running shell command: onevm show -x 12
Nov 28 14:41:57 n02 /mv[3279901]: INFO running shell command: bash -c source /var/lib/one/remotes//scripts_common.sh && ssh_make_path n01 /var/lib/one/datastores/100
Nov 28 14:41:58 n02 /mv[3279901]: INFO ssh 'n03' cmd: set -e -o pipefail && tar -C /var/lib/one/datastores/100 --sparse -cf - 12 | ssh n01 'tar -C /var/lib/one/datastores/100 --sparse -xf -' && rm -Rf /var/lib/one/datastores/100/12
Nov 28 14:42:00 n02 /mv[3279901]: ERROR command ['bash', '-c', 'source /var/lib/one/remotes//scripts_common.sh && ssh_exec_and_log "n03" "set -e -o pipefail && tar -C /var/lib/one/datastores/100 --sparse -cf - 12 | ssh n01 \'tar -C /var/lib/one/datastores/100 --sparse -xf -\' && rm -Rf /var/lib/one/datastores/100/12" "Unable to tar copy to new host"'] failed: b'ERROR: bash: Command "set -e -o pipefail && tar -C /var/lib/one/datastores/100 --sparse -cf - 12 | ssh n01 \'tar -C /var/lib/one/datastores/100 --sparse -xf -\' && rm -Rf /var/lib/one/datastores/100/12" failed: ssh: connect to host n03 port 22: No route to host\r\nUnable to tar copy to new host\n'
Nov 28 14:42:00 n02 /mv[3279901]: ERROR Traceback (most recent call last):
                                    File "/usr/lib/python3.6/site-packages/one/util.py", line 392, in run_main
                                      main_func()
                                    File "/var/lib/one/remotes/tm/linstor/mv", line 82, in main
                                      raise RuntimeError("Unable to tar copy to new host")
                                  RuntimeError: Unable to tar copy to new host
```

**Comment by rp-** [comment]
As the script comment states:
```python
    if disk_id is None:
        # this path is executed if used as system ds and as final mv call as the vm directory
```
So I guess this case was probably never really tested and of course we can't ssh copy from a down host.
So maybe we should somehow detect if the host is down here and don't throw an error,
but instead a warning that we couldn't copy any non shared data from the host.

**Comment by rp-** [comment]
There more I think about it, we might not even need the ssh copy stuff at all.
As everything we need should hopefully be in the context image, but I would need to test and check that.

**Comment by antnjakushin** [comment]
I tested this scenario again with the latest version of the addon. I get the error again and the virtual machine cannot be started on the new host.
```
Thu Jul 4 21:49:42 2024 [Z0][VM][I]: New LCM state is RUNNING
Fri Jul 5 10:43:55 2024 [Z0][VM][I]: New LCM state is UNKNOWN
Fri Jul 5 10:46:07 2024 [Z0][VM][I]: New LCM state is PROLOG_MIGRATE_UNKNOWN
Fri Jul 5 10:46:07 2024 [Z0][VM][I]: New state is ACTIVE
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/tm/linstor/mv n03:/var/lib/one//datastores/100/785/disk.0 n01:/var/lib/one//datastores/100/785/disk.0 785 101
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: Traceback (most recent call last):
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: File "/usr/lib/python3.6/site-packages/one/util.py", line 392, in run_main
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: main_func()
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: File "/var/lib/one/remotes/tm/linstor/mv", line 203, in main
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: move_linstor_resource(lin, src_host, src_path, dst_host, dst_path, dst_dir, res_name)
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: File "/var/lib/one/remotes/tm/linstor/mv", line 54, in move_linstor_resource
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: util.unlink_file(src_host, src_path)
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: File "/usr/lib/python3.6/site-packages/one/util.py", line 245, in unlink_file
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: raise RuntimeError("Error: Unable to remove symbolic link {} on {}".format(path, host))
Fri Jul 5 10:46:10 2024 [Z0][TrM][I]: RuntimeError: Error: Unable to remove symbolic link /var/lib/one/datastores/100/785/disk.0 on n03
Fri Jul 5 10:46:10 2024 [Z0][TrM][E]: Error: Unable to remove symbolic link /var/lib/one/datastores/100/785/disk.0 on n03
Fri Jul 5 10:46:10 2024 [Z0][TrM][E]: Error executing image transfer script: Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/one/util.py", line 392, in run_main main_func() File "/var/lib/one/remotes/tm/linstor/mv", line 203, in main move_linstor_resource(lin, src_host, src_path, dst_host, dst_path, dst_dir, res_name) File "/var/lib/one/remotes/tm/linstor/mv", line 54, in move_linstor_resource util.unlink_file(src_host, src_path) File "/usr/lib/python3.6/site-packages/one/util.py", line 245, in unlink_file raise RuntimeError("Error: Unable to remove symbolic link {} on {}".format(path, host)) RuntimeError: Error: Unable to remove symbolic link /var/lib/one/datastores/100/785/disk.0 on n03 ERROR: Error: Unable to remove symbolic link /var/lib/one/datastores/100/785/disk.0 on n03
Fri Jul 5 10:46:10 2024 [Z0][VM][I]: New LCM state is PROLOG_MIGRATE_UNKNOWN_FAILURE
```

My environment:
```
linstor-client        1.22.1
linstor-common        1.27.1
linstor-controller    1.27.1
linstor-opennebula    3.0.2
linstor-satellite     1.27.1
python-linstor        1.22.0
opennebula            6.6.3
```

We tested using both host hooks and the results were the same.

```
ARGUMENTS = "$TEMPLATE -m -p 2"
ARGUMENTS_STDIN = "yes"
COMMAND   = "ft/host_error.rb"
NAME      = "host_error"
STATE     = "ERROR"
REMOTE    = "no"
RESOURCE  = HOST
TYPE      = state

ARGUMENTS = "$TEMPLATE -r -f -p 2"
ARGUMENTS_STDIN = "yes"
COMMAND   = "ft/host_error.rb"
NAME      = "host_error"
STATE     = "ERROR"
REMOTE    = "no"
RESOURCE  = HOST
TYPE      = state

```

**Comment by rp-** [comment]
Can you try this small patch and rerun the test:

`/var/lib/one/remotes/tm/linstor/mv` line number 54
```python
    try:
        util.unlink_file(src_host, src_path)
    except RuntimeError:
        util.log_error("Unable to unlink file: {f} on {h}".format(f=src_path, h=src_host))
```

**Comment by antnjakushin** [comment]
This patch solves the problem. VMs successfully launched on another host.
Thanks
